---
title: "Mapping Meaning in Lyrics"
author: "Keion Vergara"
date: "2025-01-31"
format: html
bibliography: references.bibtex
nocite: |
  @*
---


## Abstract


## Overview
This project aims to analyze and visualize trends in eye pain reported on April 4th, 2024, the day of a total lunar eclipse. By leveraging geospatial analysis techniques, we will identify patterns and hotspots of eye pain accross the american states, with the hopes of understanding any correlations with environmental factors or the eclipse event itself.

:::{.column-page}
![April 8, 2024 Eclipse Path (Blue) vs. 'My Eyes Hurt' Search Volume by State. Displayed using the TMAP package [@Tennekes2018]"](map_mini.png) 
:::


## Data Collection
The data for this analysis was collected from various sources, including:

 - [Google Trends](https://trends.google.com/home): This is the main source of data, providing insights into search interest for the terms "eye pain", "eye discomfort", and related queries on April 8th, 2024. [@GoogleTrends2024]
 - [NASA Eclipse Data](https://eclipse.gsfc.nasa.gov/SEpath/SEpath2001/SE2024Apr08Tpath.html): This source provides information about the lunar eclipse path and timing for our graphic overlay. [@Espenak2024]


## References

::: {#refs}
:::
 


